import numpy as np
from sympy import primerange
from scipy.optimize import milp, Bounds, LinearConstraint
import csv

def to_tuple(vector: list[int]) -> list[int]:
    """
    Convert a "vector" representation (counts per value) into a "tuple"
    representation.

    E.g. vector = [2, 0, 1] -> tupla = [1, 1, 3]
    (value 1 appears twice, value 2 appears zero times, value 3 appears once).
    """
    tup = []
    for i in range(len(vector)):
        assert vector[i] >= 0
        tup += [i+1]*vector[i]
    return tup


def to_vector(tup: list[int], d: int) -> list[int]:
    """
    Inverse of to_tupla: convert a "tuple" into a vector 
    of counts of length d-1 (one slot per possible value 1..d-1).
    """
    vector = [0]*(d - 1)
    for elem in tup:
        vector[elem-1] += 1
    return vector


def lineals(d: int) -> list[list[int]]:
    """
    Build the linear characters for degree d as vectors: for each i in
    1..d//2, a vector with a 1 in position i and a 1 in position -i (mod d).
    """
    lineales = []
    for i in range(1,d//2 + 1):
        char = [0]*(d-1)
        char[i-1] = 1
        char[((-i)%d) - 1] = 1
        lineales.append(char)
    return lineales


def standards(d: int) -> list[list[int]]:
    """
    Build the standard characters for degree d as vectors, one family per
    prime divisor p of d. Skips indices i where k < 3*gcd(i, k), and 
    dedupes vectors already found.
    """
    P = [p for p in primerange(d) if d%p == 0]
    S = []
    for p in P:
        k = d//p
        if p == 2:
            for i in range(1,d):
                if k < 3*np.gcd(i,k):
                    continue
                spi = [0]*(d-1)
                spi[i - 1] += 1
                spi[(i+k)%d - 1] += 1
                spi[(d-2*i)%d - 1] += 1
                spi[k - 1] += 1
                if spi not in S:
                    S.append(spi)
        else:
            for i in range(1,d):
                if k < 3*np.gcd(i,k):
                    continue
                spi = [0]*(d-1)
                for j in range(p):
                    spi[(i+j*k)%d - 1] += 1
                spi[(d-p*i)%d - 1] += 1
                if spi not in S:
                    S.append(spi)
    return S


def generators(m: int, reduced: dict[int, list[int]]) -> np.ndarray:
    """
    Stack the lineal and standard generator vectors for degree d into a
    matrix, with each generator as a column (hence the transpose). Also
    appends algebraic characters lifted to degree d.
    """
    to_append = list()
    for d in reduced:
        if m == d:
            continue
        if m%d == 0:
            t = to_vector(lift(reduced[d],d,m),m)
            to_append.append(t)
    return np.array(lineals(m) + standards(m) + to_append).T


def lift(tupla: list[int], og_deg: int, new_deg: int) -> np.ndarray:
    """
    Scale a tupla defined at og_deg up to new_deg by the integer ratio
    new_deg // og_deg. Raises if new_deg is not a multiple of og_deg.
    """
    if new_deg%og_deg:
        raise Exception("Can't do it")
    return (new_deg//og_deg)*np.array(tupla, dtype=int)

def writecsv(to_write: list[dict[str, str]], filename: str, fieldnames: list[str]):
    """
    Write a .csv file
    """
    with open(filename, 'w', newline='') as csvfile:
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames, delimiter='|')
        writer.writeheader()
        writer.writerows(to_write)


def readtuples(filename: str, fieldnames: list[str,str]) -> dict[int, list[int]]:
    """
    Read a .csv file containing degree|tuple (one line per entry: d (the 
    degree), then the tuple values) into a dict mapping d -> list[int] of
    the tuple values.
    """
    d = dict()
    with open(filename, "r") as f:
        data = csv.DictReader(f, delimiter='|')
        for row in data:
            d[int(row[fieldnames[0]])] = [int(x) for x in row[fieldnames[1]].split(",")]
    return d

def reduce(A: np.ndarray, t: np.ndarray) -> np.ndarray:
    """
    Reduce the tuple t modulo the module generated by the columns of 
    matrix A by solving an integer linear program.
    Returns the rounded solution vector x, or -1 if no optimal solution
    is found.
    """
    if not isinstance(t, np.ndarray):
        t = np.array(t)

    n = A.shape[1]
    # Calculate array which at c[i] is the sum of the values of the i-th column of A
    c = np.sum(A, axis=0)

    # Scipy minimizes, we want to maximize
    minus_c = -c.astype(np.float64)
    
    # Bounds and constraints
    bounds = Bounds(np.full(n, -1.0), np.full(n, 1.0))
    integrality = np.ones(n)
    constraints = LinearConstraint(A, -np.inf, t)
    
    # solve
    res = milp(c=minus_c, constraints=constraints, integrality=integrality, bounds=bounds) # options={"disp": True} to enable progress log

    if res.success:
        # length = np.sum(t) + round(res.fun)
        return np.round(res.x).astype(int)

    else:
        print("No optimal solution was found.")
        return -1